apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: welcome-pipeline
  namespace: argocd
spec:
  destination:
    namespace: welcome-pipeline
    server: https://kubernetes.default.svc
  project: default
  source:
    path: cicd/tekton
    repoURL: https://github.com/chatapazar/welcome-deploy
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  sync:
    comparedTo:
      destination:
        namespace: welcome-pipeline
        server: https://kubernetes.default.svc
      source:
        path: cicd/tekton
        repoURL: https://github.com/chatapazar/welcome-deploy
        targetRevision: main
